config/routes.rb
Academy::Application.routes.draw do

  resources :resources
  resources :aecomo_classes
  resources :stundents

  root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/aecomo_class.rb
class AecomoClass < ActiveRecord::Base
  attr_accessible :description, :ends_at, :name, :starts_at
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  attr_accessible :description, :link, :name
end

app/models/stundent.rb
class Stundent < ActiveRecord::Base
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "50x50>" }
  
  attr_accessible :city, :email, :lastname, :name, :avatar
  
end

app/controllers/aecomo_classes_controller.rb
class AecomoClassesController < ApplicationController
  # GET /aecomo_classes
  # GET /aecomo_classes.json
  def index
    @aecomo_classes = AecomoClass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aecomo_classes }
      format.xml { render xml: @aecomo_classes }
    end
  end

  # GET /aecomo_classes/1
  # GET /aecomo_classes/1.json
  def show
    @aecomo_class = AecomoClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aecomo_class }
    end
  end

  # GET /aecomo_classes/new
  # GET /aecomo_classes/new.json
  def new
    @aecomo_class = AecomoClass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aecomo_class }
    end
  end

  # GET /aecomo_classes/1/edit
  def edit
    @aecomo_class = AecomoClass.find(params[:id])
  end

  # POST /aecomo_classes
  # POST /aecomo_classes.json
  def create
    @aecomo_class = AecomoClass.new(params[:aecomo_class])

    respond_to do |format|
      if @aecomo_class.save
        format.html { redirect_to @aecomo_class, notice: 'Aecomo class was successfully created.' }
        format.json { render json: @aecomo_class, status: :created, location: @aecomo_class }
      else
        format.html { render action: "new" }
        format.json { render json: @aecomo_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aecomo_classes/1
  # PUT /aecomo_classes/1.json
  def update
    @aecomo_class = AecomoClass.find(params[:id])

    respond_to do |format|
      if @aecomo_class.update_attributes(params[:aecomo_class])
        format.html { redirect_to @aecomo_class, notice: 'Aecomo class was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aecomo_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aecomo_classes/1
  # DELETE /aecomo_classes/1.json
  def destroy
    @aecomo_class = AecomoClass.find(params[:id])
    @aecomo_class.destroy

    respond_to do |format|
      format.html { redirect_to aecomo_classes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resources }
      format.xml { render xml: @resources }
    end
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
    @resource = Resource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resource }
    end
  end

  # GET /resources/new
  # GET /resources/new.json
  def new
    @resource = Resource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resource }
    end
  end

  # GET /resources/1/edit
  def edit
    @resource = Resource.find(params[:id])
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(params[:resource])

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render json: @resource, status: :created, location: @resource }
      else
        format.html { render action: "new" }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resources/1
  # PUT /resources/1.json
  def update
    @resource = Resource.find(params[:id])

    respond_to do |format|
      if @resource.update_attributes(params[:resource])
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy

    respond_to do |format|
      format.html { redirect_to resources_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stundents_controller.rb
class StundentsController < ApplicationController
  # GET /stundents
  # GET /stundents.json
  def index
    @stundents = Stundent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stundents }
    end
  end

  # GET /stundents/1
  # GET /stundents/1.json
  def show
    @stundent = Stundent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stundent }
    end
  end

  # GET /stundents/new
  # GET /stundents/new.json
  def new
    @stundent = Stundent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stundent }
    end
  end

  # GET /stundents/1/edit
  def edit
    @stundent = Stundent.find(params[:id])
  end

  # POST /stundents
  # POST /stundents.json
  def create
    @stundent = Stundent.new(params[:stundent])

    respond_to do |format|
      if @stundent.save
        format.html { redirect_to @stundent, notice: 'Stundent was successfully created.' }
        format.json { render json: @stundent, status: :created, location: @stundent }
      else
        format.html { render action: "new" }
        format.json { render json: @stundent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stundents/1
  # PUT /stundents/1.json
  def update
    @stundent = Stundent.find(params[:id])

    respond_to do |format|
      if @stundent.update_attributes(params[:stundent])
        format.html { redirect_to @stundent, notice: 'Stundent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stundent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stundents/1
  # DELETE /stundents/1.json
  def destroy
    @stundent = Stundent.find(params[:id])
    @stundent.destroy

    respond_to do |format|
      format.html { redirect_to stundents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/aecomo_classes_helper.rb
module AecomoClassesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/stundents_helper.rb
module StundentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aecomo_classes/_form.html.erb
<%= form_for(@aecomo_class) do |f| %>
  <% if @aecomo_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aecomo_class.errors.count, "error") %> prohibited this aecomo_class from being saved:</h2>

      <ul>
      <% @aecomo_class.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aecomo_classes/edit.html.erb
<h1>Editing aecomo_class</h1>

<%= render 'form' %>

<%= link_to 'Show', @aecomo_class %> |
<%= link_to 'Back', aecomo_classes_path %>

app/views/aecomo_classes/index.html.erb
<h1>Listing aecomo_classes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aecomo_classes.each do |aecomo_class| %>
  <tr>
    <td><%= aecomo_class.name %></td>
    <td><%= aecomo_class.starts_at %></td>
    <td><%= aecomo_class.ends_at %></td>
    <td><%= aecomo_class.description %></td>
    <td><%= link_to 'Show', aecomo_class %></td>
    <td><%= link_to 'Edit', edit_aecomo_class_path(aecomo_class) %></td>
    <td><%= link_to 'Destroy', aecomo_class, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Aecomo class', new_aecomo_class_path %>

app/views/aecomo_classes/new.html.erb
<h1>New aecomo_class</h1>

<%= render 'form' %>

<%= link_to 'Back', aecomo_classes_path %>

app/views/aecomo_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @aecomo_class.name %>
</p>

<p>
  <b>Starts at:</b>
  <%= @aecomo_class.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @aecomo_class.ends_at %>
</p>

<p>
  <b>Description:</b>
  <%= @aecomo_class.description %>
</p>


<%= link_to 'Edit', edit_aecomo_class_path(@aecomo_class) %> |
<%= link_to 'Back', aecomo_classes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> 
  <html lang="en"> 
<!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <div class="row">
      <nav>
        <ul class="nav-bar">
          <li>
            <%= link_to "Home", root_path() %>
          </li>
          <li>
            <%= link_to "Alumnos", stundents_path() %>
          </li>
          <li>
            <%= link_to "Clases", aecomo_classes_path() %>
          </li>
          <li>
            <%= link_to "Recursos", resources_path() %>
          </li>
        </ul>      
      </nav>      
    </div>

    <div id="main" class="row">
      <%= yield %>  
    </div>
    
    <div id="footer" class="row">
      <div class="four columns offset-by-eight">
        <%= link_to "Softwhisper SL", "http://softwhisper.es" %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Link</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= resource.link %></td>
    <td><%= resource.description %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>

<p>
  <b>Link:</b>
  <%= @resource.link %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/stundents/_form.html.erb
<%= form_for @stundent, :html => { :multipart => true } do |f| %>
  <% if @stundent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stundent.errors.count, "error") %> prohibited this stundent from being saved:</h2>

      <ul>
      <% @stundent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">  
    <div class="eight columns">    
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :lastname %>
      <%= f.text_field :lastname %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="four columns">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
    <br />
    <div class="twelve columns">
      <%= f.submit :class => "button" %>
    </div>
  </div>
<% end %>

app/views/stundents/edit.html.erb
<h1>Editing stundent</h1>

<%= render 'form' %>

<%= link_to 'Show', @stundent %> |
<%= link_to 'Back', stundents_path %>

app/views/stundents/index.html.erb
<div class="twelve column">
  <h1>Alumnos</h1>
  <%= link_to 'Agregar', new_stundent_path, :class => "small radius button" %>
  <br /><br />
  <table>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>City</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @stundents.each do |stundent| %>
    <tr>
      <td><%= stundent.name %></td>
      <td><%= stundent.lastname %></td>
      <td><%= stundent.city %></td>
      <td><%= stundent.email %></td>
      <td><%= link_to 'Show', stundent %></td>
      <td><%= link_to 'Edit', edit_stundent_path(stundent) %></td>
      <td><%= link_to 'Destroy', stundent, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/stundents/new.html.erb
<h1>Alta de Alumnos</h1>  

<%= render 'form' %>

<%= link_to 'Back', stundents_path, :class => "alert button" %>

app/views/stundents/show.html.erb
<div class="eight columns">
  <p id="notice"><%= notice %></p>
  <p>
    <b>Name:</b>
    <%= @stundent.name %>
  </p>
  <p>
    <b>Lastname:</b>
    <%= @stundent.lastname %>
  </p>
  <p>
    <b>City:</b>
    <%= @stundent.city %>
  </p>
  <p>
    <b>Email:</b>
    <%= @stundent.email %>
  </p>
</div>
<div class="four columns">
  <%= image_tag @stundent.avatar.url(:medium) %>
</div>

<%= link_to 'Edit', edit_stundent_path(@stundent) %> |
<%= link_to 'Back', stundents_path %>

app/views/welcome/index.html.erb
<div class="six columns">
  <h1>Curso iOS</h1>
  <p>
    Desde esta aplicación podremos acceder a los servicios de prueba desarrollados para el curso de iOS de AecomoAcademy. 
    Cada uno de los servicios está documentado en su sección accesible desde el menú superior.
  </p>
  <p>
    El código de esta aplicación está disponible en GitHub.
  </p>
</div>